adjust snappy packaging for series 16

diff --git a/snappy-packaging/bin/init b/snappy-packaging/bin/init
--- a/snappy-packaging/bin/init
+++ b/snappy-packaging/bin/init
@@ -1,11 +1,16 @@
 #!/bin/sh
 
-upgrade_path="$SNAP_APP_DATA_PATH/.upgraded_${SNAP_VERSION}"
-
-# ufw.srv will have already done this on install.
-if [ ! -e "$upgrade_path" ]; then
-    echo "Rules not found in '$SNAP_APP_DATA_PATH'. Aborting"
+if [ -z "$SNAP" ]; then
+    echo "SNAP not set"
     exit 1
 fi
 
-./lib/ufw/ufw-init --rootdir "$SNAP_APP_PATH" --datadir "$SNAP_APP_DATA_PATH" "$@"
+upgrade_path="$SNAP_DATA/.upgraded_${SNAP_VERSION}"
+
+# ufw.srv will have already done this on install.
+if [ ! -e "$upgrade_path" ]; then
+    echo "Rules not found in '$SNAP_DATA'. Aborting"
+    exit 1
+fi
+
+"$SNAP"/lib/ufw/ufw-init --rootdir "$SNAP" --datadir "$SNAP_DATA" "$@"
