update check-requirements to prompt before tests that might autoload kernel modules

diff --git a/tests/check-requirements b/tests/check-requirements
--- a/tests/check-requirements
+++ b/tests/check-requirements
@@ -3,7 +3,7 @@
 # check-requirements: verify all the required iptables functionality is
 # available
 #
-# Copyright 2008-2010 Canonical Ltd.
+# Copyright 2008-2011 Canonical Ltd.
 #
 #    This program is free software: you can redistribute it and/or modify
 #    it under the terms of the GNU General Public License version 3,
@@ -86,6 +86,18 @@ if [ -n "$error" ]; then
     exit 1
 fi
 echo ""
+
+echo "This script will now attempt to create various rules using the iptables"
+echo "and ip6tables commands. This may result in module autoloading (eg, for"
+echo "IPv6)."
+if [ "$1" != "-f" ]; then
+    echo -n "Proceed with checks (Y/n)? "
+    read ans
+    if [ "$ans" = "n" ] || [ "$ans" = "N" ] || [ "$ans" = "no" ]; then
+        echo "Aborting"
+        exit 1
+    fi
+fi
 
 # check modules
 for i in "" 6; do
