tests/check-requirements: update for rpfilter and conn helper sysctl and target

diff --git a/tests/check-requirements b/tests/check-requirements
--- a/tests/check-requirements
+++ b/tests/check-requirements
@@ -3,7 +3,7 @@
 # check-requirements: verify all the required iptables functionality is
 # available
 #
-# Copyright 2008-2014 Canonical Ltd.
+# Copyright 2008-2018 Canonical Ltd.
 #
 #    This program is free software: you can redistribute it and/or modify
 #    it under the terms of the GNU General Public License version 3,
@@ -93,7 +93,7 @@ fi
 echo ""
 
 # check /proc
-for i in /proc/net/dev /proc/net/if_inet6; do
+for i in /proc/net/dev /proc/net/if_inet6 /proc/sys/net/netfilter/nf_conntrack_helper; do
     echo -n "Has $i: "
     if [ ! -e "$i" ]; then
         echo "no"
@@ -136,13 +136,15 @@ for i in "" 6; do
         echo "== IPv4 =="
     fi
 
-    echo -n "Creating '$c'... "
-    $exe -N "$c" || {
-        echo "ERROR: could not create '$c'. Aborting" >&2
-        error="yes"
-        break
-    }
-    echo "done"
+    for tbl in filter raw ; do
+        echo -n "Creating '$c' in $tbl table... "
+        $exe -N "$c" -t $tbl || {
+            echo "ERROR: could not create '$c'. Aborting" >&2
+            error="yes"
+            break
+        }
+        echo "done"
+    done
 
     # set up a RETURN rule right at the top, so we don't open anything up when
     # running the script. Isn't attached to INPUT, but better safe than sorry.
@@ -203,6 +205,19 @@ for i in "" 6; do
     echo -n "comment: "
     runcmd $exe -A $c -m comment --comment 'dapp_Samba'
 
+    echo -n "CT: "
+    runcmd $exe -t raw -A $c -j CT
+
+    # ftp isn't strictly needed, but we need to test helpers in some manner
+    echo -n "CT --helper ftp: "
+    runcmd $exe -t raw -A $c -p tcp --dport 21 -j CT --helper ftp
+
+    echo -n "ctstate RELATED --helper ftp: "
+    runcmd $exe -A $c -m conntrack --ctstate RELATED -m helper --helper ftp -p tcp --dport 1024: -j ACCEPT
+
+    echo -n "rpfilter: "
+    runcmd $exe -t raw -A $c -m rpfilter --invert -j DROP
+
     if [ -z "$i" ]; then
         for j in LOCAL MULTICAST BROADCAST; do
             echo -n "addrtype ($j): "
@@ -239,19 +254,23 @@ for i in "" 6; do
         exe="ip6tables"
         c="${chain}6"
     fi
-    $exe -F $c >/dev/null 2>&1 || {
-        if [ -z "$error" ]; then
-            echo "ERROR: could not flush '$c'" >&2
-            error="yes"
-        fi
-    }
-    $exe -X $c >/dev/null 2>&1 || {
-        if [ -z "$error" ]; then
-            error="yes"
-            echo "ERROR: could not remove '$c'" >&2
-        fi
-    }
+    for tbl in filter raw ; do
+        $exe -F $c -t $tbl >/dev/null 2>&1 || {
+            if [ -z "$error" ]; then
+                echo "ERROR: could not flush '$c'" >&2
+                error="yes"
+            fi
+        }
+        $exe -X $c -t $tbl >/dev/null 2>&1 || {
+            if [ -z "$error" ]; then
+                error="yes"
+                echo "ERROR: could not remove '$c'" >&2
+            fi
+        }
+    done
 done
+# this will fail if there are any rules that use it, so ignore that
+modprobe -r nf_conntrack_ftp >/dev/null 2>&1 || true
 
 if [ -n "$error" ] || [ -n "$error_runtime" ]; then
     if [ -n "$error" ]; then
